---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "vacation"
    labels: 
      app: "vacation"
  spec: 
    selector: 
      matchLabels: 
        app: "vacation"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "vacation"
      spec: 
        containers: 
          - 
            name: "vacation"
            image: "vacation"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "vacation"
    labels: 
      app: "vacation"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "vacation"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "schedule"
    labels: 
      app: "schedule"
  spec: 
    selector: 
      matchLabels: 
        app: "schedule"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "schedule"
      spec: 
        containers: 
          - 
            name: "schedule"
            image: "schedule"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "schedule"
    labels: 
      app: "schedule"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "schedule"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "employee"
    labels: 
      app: "employee"
  spec: 
    selector: 
      matchLabels: 
        app: "employee"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "employee"
      spec: 
        containers: 
          - 
            name: "employee"
            image: "employee"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "employee"
    labels: 
      app: "employee"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "employee"
